# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import outbound_call_pb2 as outbound__call__pb2


class CampaignOutboundCallChargeStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExecutePaymentTransaction = channel.unary_unary(
            "/CampaignOutboundCall.CampaignOutboundCallCharge/ExecutePaymentTransaction",
            request_serializer=outbound__call__pb2.CampiagnOutboundCallRequest.SerializeToString,
            response_deserializer=outbound__call__pb2.GrpcResponse.FromString,
        )


class CampaignOutboundCallChargeServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ExecutePaymentTransaction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_CampaignOutboundCallChargeServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "ExecutePaymentTransaction": grpc.unary_unary_rpc_method_handler(
            servicer.ExecutePaymentTransaction,
            request_deserializer=outbound__call__pb2.CampiagnOutboundCallRequest.FromString,
            response_serializer=outbound__call__pb2.GrpcResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "CampaignOutboundCall.CampaignOutboundCallCharge", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class CampaignOutboundCallCharge(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ExecutePaymentTransaction(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/CampaignOutboundCall.CampaignOutboundCallCharge/ExecutePaymentTransaction",
            outbound__call__pb2.CampiagnOutboundCallRequest.SerializeToString,
            outbound__call__pb2.GrpcResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
