# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: workspace_credit.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x16workspace_credit.proto\x12\x10workspace_credit".\n\x16WorkspaceCreditRequest\x12\x14\n\x0cworkspace_id\x18\x01 \x01(\t"3\n\x17WorkspaceCreditResponse\x12\x18\n\x10workspace_credit\x18\x01 \x01(\x02\x32~\n\x0fWorkspaceCredit\x12k\n\x12GetWorkspaceCredit\x12(.workspace_credit.WorkspaceCreditRequest\x1a).workspace_credit.WorkspaceCreditResponse"\x00\x62\x06proto3'
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "workspace_credit_pb2", globals()
)
if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    _WORKSPACECREDITREQUEST._serialized_start = 44
    _WORKSPACECREDITREQUEST._serialized_end = 90
    _WORKSPACECREDITRESPONSE._serialized_start = 92
    _WORKSPACECREDITRESPONSE._serialized_end = 143
    _WORKSPACECREDIT._serialized_start = 145
    _WORKSPACECREDIT._serialized_end = 271
# @@protoc_insertion_point(module_scope)
