# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: foundation.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x10\x66oundation.proto\x12\nfoundation"?\n\x10WorkspaceDetails\x12\x14\n\x0cworkspace_id\x18\x01 \x01(\t\x12\x15\n\rprovider_type\x18\x02 \x01(\t"\xb1\x01\n\x0fProviderDetails\x12\x16\n\x0eworkspace_name\x18\x01 \x01(\t\x12\x15\n\rprovider_type\x18\x02 \x01(\t\x12\x0f\n\x07\x61uth_id\x18\x03 \x01(\t\x12\x12\n\nauth_token\x18\x04 \x01(\t\x12\x0f\n\x07\x61pi_key\x18\x05 \x01(\t\x12\x12\n\napi_secret\x18\x06 \x01(\t\x12\x14\n\x0ckyc_verified\x18\x07 \x01(\x08\x12\x0f\n\x07success\x18\x08 \x01(\x08"/\n\x17PlanSubscriptionRequest\x12\x14\n\x0cworkspace_id\x18\x01 \x01(\t"m\n\x18PlanSubscriptionResponse\x12\x0f\n\x07plan_id\x18\x01 \x01(\t\x12\x12\n\nplan_title\x18\x02 \x01(\t\x12\x1b\n\x13subscription_status\x18\x03 \x01(\t\x12\x0f\n\x07success\x18\x04 \x01(\x08"H\n\x1aGetWorkspaceFeatureRequest\x12\x14\n\x0cworkspace_id\x18\x01 \x01(\t\x12\x14\n\x0c\x66\x65\x61ture_name\x18\x02 \x01(\t"H\n\x10WorkspaceFeature\x12\n\n\x02id\x18\x01 \x01(\t\x12\x14\n\x0cworkspace_id\x18\x02 \x01(\t\x12\x12\n\nis_enabled\x18\x03 \x01(\x08\x32\xa5\x02\n\rFoundationRPC\x12Q\n\x12GetProviderDetails\x12\x1c.foundation.WorkspaceDetails\x1a\x1b.foundation.ProviderDetails"\x00\x12]\n\x13GetWorkspaceFeature\x12&.foundation.GetWorkspaceFeatureRequest\x1a\x1c.foundation.WorkspaceFeature"\x00\x12\x62\n\x13GetPlanSubscription\x12#.foundation.PlanSubscriptionRequest\x1a$.foundation.PlanSubscriptionResponse"\x00\x32y\n\x13PlanSubscriptionRPC\x12\x62\n\x13GetPlanSubscription\x12#.foundation.PlanSubscriptionRequest\x1a$.foundation.PlanSubscriptionResponse"\x00\x62\x06proto3'
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "foundation_pb2", globals()
)
if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    _WORKSPACEDETAILS._serialized_start = 32
    _WORKSPACEDETAILS._serialized_end = 95
    _PROVIDERDETAILS._serialized_start = 98
    _PROVIDERDETAILS._serialized_end = 275
    _PLANSUBSCRIPTIONREQUEST._serialized_start = 277
    _PLANSUBSCRIPTIONREQUEST._serialized_end = 324
    _PLANSUBSCRIPTIONRESPONSE._serialized_start = 326
    _PLANSUBSCRIPTIONRESPONSE._serialized_end = 435
    _GETWORKSPACEFEATUREREQUEST._serialized_start = 437
    _GETWORKSPACEFEATUREREQUEST._serialized_end = 509
    _WORKSPACEFEATURE._serialized_start = 511
    _WORKSPACEFEATURE._serialized_end = 583
    _FOUNDATIONRPC._serialized_start = 586
    _FOUNDATIONRPC._serialized_end = 879
    _PLANSUBSCRIPTIONRPC._serialized_start = 881
    _PLANSUBSCRIPTIONRPC._serialized_end = 1002
# @@protoc_insertion_point(module_scope)
